// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Core101.Model.Entity
{
    public partial class Task
    {
        public int TaskID { get; set; }
        public string ProjectCode { get; set; }
        public string TaskCode { get; set; }
        public string Brand { get; set; }
        public string Costcenter { get; set; }
        public decimal? Revenue { get; set; }
        public decimal? Cost { get; set; }
        public int? GenerateMARevenue { get; set; }
        public int? GenerateMACost { get; set; }
    }
}